// src/components/MeterReading/components/PropertyInfoHeader.tsx
interface PropertyInfoHeaderProps {
  propertyName: string;
  roomName: string;
}

const PropertyInfoHeader = ({ propertyName, roomName }: PropertyInfoHeaderProps) => (
  <div className="property-info-card">
    <h2 className="property-name">{String(propertyName || '物件名未設定')}</h2>
    <p className="room-info">部屋: {String(roomName || '部屋名未設定')}</p>
  </div>
);

export default PropertyInfoHeader;

// src/components/MeterReading/components/PropertyInfoHeader.svelte
<script lang="ts">
  import { PROPERTY_NAME_UNSET, ROOM_NAME_UNSET } from '../../../constants/messages';

  interface Props {
    propertyName: string;
    roomName: string;
  }

  let { propertyName, roomName }: Props = $props();
</script>

<div class="property-info-card">
  <h2 class="property-name">{String(propertyName || PROPERTY_NAME_UNSET)}</h2>
  <p class="room-info">部屋: {String(roomName || ROOM_NAME_UNSET)}</p>
</div>
