// src/components/MeterReading/MeterReadingApp.svelte
<script lang="ts">
  import { formatReading, calculateUsageDisplay } from './utils/formatUtils';
  import { mapReadingFromApi } from './utils/readingMapper';
  import { calculateWarningFlag } from './utils/warningFlag';
  import { createMeterReadings } from './hooks/useMeterReadings.svelte';
  import { createRoomNavigation } from './hooks/useRoomNavigation.svelte';
  import { createToast } from './hooks/useToast.svelte';
  import { gasFetch } from '../../utils/gasClient';
  import LoadingOverlay from './components/LoadingOverlay.svelte';
  import ToastOverlay from './components/ToastOverlay.svelte';
  import NavigationButtons from './components/NavigationButtons.svelte';
  import PropertyInfoHeader from './components/PropertyInfoHeader.svelte';
  import ReadingHistoryTable from './components/ReadingHistoryTable.svelte';
  import InitialReadingForm from './components/InitialReadingForm.svelte';
  import NetworkStatusBar from '../NetworkStatusBar.svelte';

  import type { MeterReading } from '../../types';

  // ── Core state stores ──
  const readings = createMeterReadings();
  const toast = createToast();

  let readingValues = $state<Record<string, string>>({});
  let inputErrors = $state<Record<string, string>>({});
  let usageStates = $state<Record<string, string>>({});

  // Mutable flag — does NOT need to trigger re-renders.
  // Tracks whether reading was successfully saved for optimistic cache update.
  let hasSaved = false;

  // ── Derived: whether any reading has a valid previousReading ──
  let hasReadingsWithPrevious = $derived(
    Array.isArray(readings.meterReadings) &&
      readings.meterReadings.length > 0 &&
      readings.meterReadings.some(
        (r: MeterReading) =>
          r.previousReading && r.previousReading !== '' && r.previousReading !== 0
      )
  );

  // ── Initialize readingValues when meterReadings changes ──
  $effect(() => {
    const current = readings.meterReadings;
    if (current.length > 0) {
      const updated = { ...readingValues };
      let changed = false;
      current.forEach((reading: MeterReading) => {
        if (!(reading.date in updated)) {
          updated[reading.date] = formatReading(reading.currentReading);
          changed = true;
        }
      });
      if (!('' in updated)) {
        updated[''] = '';
        changed = true;
      }
      if (changed) readingValues = updated;
    }
  });

  // ── Room navigation (created after readings store is available) ──
  const navigation = createRoomNavigation({
    get propertyId() {
      return readings.propertyId;
    },
    get roomId() {
      return readings.roomId;
    },
    get gasWebAppUrl() {
      return readings.gasWebAppUrl;
    },
    get displayToast() {
      return toast.displayToast;
    },
    get onNavigateToRoom() {
      return (targetRoomId: string, preloadedNavData?: Record<string, unknown>) => {
        hasSaved = false;
        const newUrl = `/reading/?propertyId=${encodeURIComponent(readings.propertyId)}&roomId=${encodeURIComponent(targetRoomId)}`;
        window.history.replaceState(null, '', newUrl);

        // If integrated API returned navigation data, use it directly (no extra fetch)
        if (preloadedNavData && preloadedNavData.readings) {
          const newReadings = Array.isArray(preloadedNavData.readings)
            ? preloadedNavData.readings.map((raw: Record<string, unknown>, index: number) =>
                mapReadingFromApi(raw, index, { calculateWarnings: true })
              )
            : [];
          readings.roomId = targetRoomId;
          readings.meterReadings = newReadings;
          readings.propertyName = String(preloadedNavData.propertyName || readings.propertyName);
          readings.roomName = String(preloadedNavData.roomName || readings.roomName);

          const newValues: Record<string, string> = { '': '' };
          newReadings.forEach((reading: MeterReading) => {
            newValues[reading.date] = formatReading(reading.currentReading);
          });
          readingValues = newValues;
          inputErrors = {};
          usageStates = {};
          navigation.updating = false;
          window.scrollTo(0, 0);
          return;
        }

        // Fallback: fetch room data separately
        readings
          .loadMeterReadings(readings.propertyId, targetRoomId, 3, true)
          .then((newReadings: MeterReading[] | null) => {
            const newValues: Record<string, string> = { '': '' };
            if (newReadings && Array.isArray(newReadings)) {
              newReadings.forEach((reading: MeterReading) => {
                newValues[reading.date] = formatReading(reading.currentReading);
              });
            }
            readingValues = newValues;
            inputErrors = {};
            usageStates = {};
            navigation.updating = false;
            window.scrollTo(0, 0);
          })
          .catch(() => {
            navigation.updating = false;
          });
      };
    },
  });

  // ── Helpers ──

  function getCurrentJSTDateString(): string {
    return new Intl.DateTimeFormat('ja-CA', {
      timeZone: 'Asia/Tokyo',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }).format(new Date());
  }

  function collectReadingsFromState(): Record<string, unknown>[] {
    const result: Record<string, unknown>[] = [];

    for (const reading of readings.meterReadings) {
      const date = reading.date;
      const originalValue = formatReading(reading.currentReading);
      const currentValue = readingValues[date] ?? originalValue;

      if (currentValue && currentValue !== originalValue && currentValue.trim() !== '') {
        const numericValue = parseFloat(currentValue);
        if (!isNaN(numericValue) && numericValue >= 0) {
          result.push({
            date: getCurrentJSTDateString(),
            currentReading: currentValue,
            warningFlag: reading.warningFlag || '正常',
          });
        }
      }
    }

    // Also check initial reading form (empty date key)
    const initialValue = readingValues[''] ?? '';
    if (initialValue && initialValue.trim() !== '') {
      const numericValue = parseFloat(initialValue);
      if (!isNaN(numericValue) && numericValue >= 0) {
        result.push({
          date: getCurrentJSTDateString(),
          currentReading: initialValue,
          warningFlag: '正常',
        });
      }
    }

    return result;
  }

  function handleInputChange(date: string, value: string, reading: MeterReading): void {
    readingValues = { ...readingValues, [date]: value };
    const previousValue = formatReading(reading.previousReading);
    const numericValue = parseFloat(value);

    if (value === '') {
      inputErrors = { ...inputErrors, [date]: '' };
      usageStates = { ...usageStates, [date]: calculateUsageDisplay(value, previousValue) };
    } else if (isNaN(numericValue) || numericValue < 0) {
      inputErrors = { ...inputErrors, [date]: '0以上の数値を入力' };
      usageStates = { ...usageStates, [date]: '-' };
    } else {
      inputErrors = { ...inputErrors, [date]: '' };
      const usageDisplay = calculateUsageDisplay(value, previousValue);
      usageStates = { ...usageStates, [date]: usageDisplay };

      // Real-time warning flag calculation
      const previousReadingValue = parseFloat(String(reading.previousReading)) || 0;
      const previousPreviousReadingValue = parseFloat(String(reading.previousPreviousReading)) || 0;
      const threeTimesPreviousReadingValue = parseFloat(String(reading.threeTimesPrevious)) || 0;

      const warningResult = calculateWarningFlag(
        numericValue,
        previousReadingValue,
        previousPreviousReadingValue,
        threeTimesPreviousReadingValue
      );

      readings.meterReadings = readings.meterReadings.map((r: MeterReading) =>
        r.date === date
          ? {
              ...r,
              warningFlag: warningResult.warningFlag,
              standardDeviation: warningResult.standardDeviation,
            }
          : r
      );
    }
  }

  function handleInitialInputChange(value: string): void {
    const dateForDataAttribute = '';
    readingValues = { ...readingValues, '': value };
    const numericValue = parseFloat(value);

    if (value === '') {
      inputErrors = {
        ...inputErrors,
        [dateForDataAttribute]: '初回検針では指示数の入力が必須です。',
      };
      usageStates = { ...usageStates, [dateForDataAttribute]: '-' };
    } else if (isNaN(numericValue) || numericValue < 0) {
      inputErrors = { ...inputErrors, [dateForDataAttribute]: '0以上の数値を入力してください。' };
      usageStates = { ...usageStates, [dateForDataAttribute]: '-' };
    } else {
      inputErrors = { ...inputErrors, [dateForDataAttribute]: '' };
      usageStates = { ...usageStates, [dateForDataAttribute]: calculateUsageDisplay(value, '') };
    }
  }

  async function handleUpdateReadings(): Promise<void> {
    const { propertyId, roomId, meterReadings } = readings;

    if (!propertyId || !roomId) {
      toast.displayToast('物件IDまたは部屋IDが取得できませんでした。');
      return;
    }

    // Validate: check for empty required fields
    let hasValidationErrors = false;
    if (hasReadingsWithPrevious) {
      // Regular readings: validate each entry's date-keyed value
      for (const reading of meterReadings) {
        const date = reading.date;
        const originalValue = formatReading(reading.currentReading);
        const currentValue = readingValues[date] ?? originalValue;

        if (originalValue === '' && (!currentValue || currentValue.trim() === '')) {
          inputErrors = { ...inputErrors, [date]: '初回検針では指示数の入力が必須です。' };
          hasValidationErrors = true;
        }
      }
    } else {
      // Initial reading: validate the InitialReadingForm value (stored under '' key)
      const initialValue = readingValues[''] ?? '';
      if (!initialValue || initialValue.trim() === '') {
        inputErrors = { ...inputErrors, '': '初回検針では指示数の入力が必須です。' };
        hasValidationErrors = true;
      }
    }

    if (hasValidationErrors) {
      toast.displayToast('入力値に誤りがあります。各項目のエラーを確認してください。');
      return;
    }

    const updatedReadings = collectReadingsFromState();

    if (updatedReadings.length === 0) {
      toast.displayToast('更新するデータがありません。');
      return;
    }

    navigation.updating = true;

    try {
      const result = (await gasFetch(
        'updateMeterReadings',
        {
          propertyId,
          roomId,
          readings: JSON.stringify(updatedReadings),
        },
        'GET'
      )) as Record<string, unknown>;

      if (result.success) {
        hasSaved = true;
        toast.displayToast('検針データが正常に更新されました');
        inputErrors = {};
        // Invalidate prefetch cache so next navigation fetches fresh data
        readings.invalidatePrefetch(readings.propertyId, readings.roomId);
      } else {
        throw new Error((result.error as string) || '指示数の更新に失敗しました。');
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      toast.displayToast('更新エラー: ' + message);
    } finally {
      navigation.updating = false;
    }
  }

  // ── Derived: room navigation info ──
  let roomNav = $derived(navigation.getRoomNavigation());

  // ── Prefetch adjacent rooms after data loads ──
  $effect(() => {
    const current = readings.meterReadings;
    const isLoading = readings.loading;
    const hasError = readings.error;
    if (isLoading || hasError || !current) return;

    const propId = readings.propertyId;
    if (!propId) return;

    const nav = navigation.getRoomNavigation();
    if (nav.previousRoom?.id) {
      readings.prefetchRoom(propId, nav.previousRoom.id);
    }
    if (nav.nextRoom?.id) {
      readings.prefetchRoom(propId, nav.nextRoom.id);
    }
  });
</script>

<!-- ═══════════════ Loading state ═══════════════ -->
{#if readings.loading}
  <NetworkStatusBar />
  <a href="#main-content" class="skip-link"> メインコンテンツへ </a>
  <div class="app-header">
    <button
      onclick={() => navigation.handleBackButton(readings.propertyId, readings.roomId, hasSaved)}
      class="back-button"
      aria-label="戻る"
    >
      &lt;
    </button>
    <h1 class="header-title">検針情報</h1>
  </div>
  <div id="main-content" class="content-area mantine-container">
    <div class="mantine-stack center">
      <div class="mantine-loader"></div>
      <p class="mantine-text">検針データを読み込んでいます...</p>
    </div>
  </div>

  <!-- ═══════════════ Error state ═══════════════ -->
{:else if readings.error}
  <NetworkStatusBar />
  <a href="#main-content" class="skip-link"> メインコンテンツへ </a>
  <div class="app-header">
    <button
      onclick={() => navigation.handleBackButton(readings.propertyId, readings.roomId, hasSaved)}
      class="back-button"
      aria-label="戻る"
    >
      &lt;
    </button>
    <h1 class="header-title">検針情報</h1>
  </div>
  <div id="main-content" class="content-area mantine-container">
    <div class="mantine-stack">
      <div class="mantine-alert">
        <h3 class="mantine-text weight-600">エラー</h3>
        <p class="mantine-text">{String(readings.error || 'エラーが発生しました')}</p>
      </div>
    </div>
  </div>

  <!-- ═══════════════ Main content ═══════════════ -->
{:else}
  {#if navigation.isNavigating}
    <LoadingOverlay message={navigation.navigationMessage} />
  {:else if navigation.updating}
    <LoadingOverlay message="移動中..." />
  {/if}

  <NetworkStatusBar />
  <a href="#main-content" class="skip-link"> メインコンテンツへ </a>
  <div class="app-header">
    <button
      onclick={() => navigation.handleBackButton(readings.propertyId, readings.roomId, hasSaved)}
      class="back-button"
      aria-label="戻る"
    >
      &lt;
    </button>
    <h1 class="header-title">検針情報</h1>
  </div>

  <div id="main-content" class="content-area mantine-container">
    <div class="mantine-stack">
      <PropertyInfoHeader propertyName={readings.propertyName} roomName={readings.roomName} />
      <div
        class="mantine-paper reading-history-container"
        style="padding: var(--mui-spacing-xs); margin: 0;"
      >
        <div class="reading-history-header">
          <NavigationButtons
            hasPrevious={roomNav.hasPrevious}
            hasNext={roomNav.hasNext}
            disabled={navigation.updating}
            onPrevious={() => navigation.handlePreviousRoom(collectReadingsFromState)}
            onNext={() => navigation.handleNextRoom(collectReadingsFromState)}
            variant="header"
          />
        </div>

        {#if hasReadingsWithPrevious}
          <ReadingHistoryTable
            meterReadings={readings.meterReadings}
            {readingValues}
            {inputErrors}
            {usageStates}
            onInputChange={handleInputChange}
          />

          <NavigationButtons
            hasPrevious={roomNav.hasPrevious}
            hasNext={roomNav.hasNext}
            disabled={navigation.updating}
            onPrevious={() => navigation.handlePreviousRoom(collectReadingsFromState)}
            onNext={() => navigation.handleNextRoom(collectReadingsFromState)}
            variant="footer"
          />
        {:else}
          <InitialReadingForm
            readingValue={readingValues[''] ?? ''}
            inputError={inputErrors[''] ?? ''}
            usageState={usageStates[''] ?? ''}
            onInputChange={handleInitialInputChange}
          />
        {/if}
      </div>
    </div>

    {#if !readings.loading && !readings.error}
      <div class="fab-container" style="position: fixed; bottom: 20px; right: 20px; z-index: 1001;">
        <button
          class="fab-button mantine-button variant-filled"
          onclick={handleUpdateReadings}
          disabled={navigation.updating || navigation.isNavigating || !navigator.onLine}
          title={hasReadingsWithPrevious ? '指示数を更新' : '初回検針データを保存'}
          style="width: 72px; height: 72px; border-radius: 50%; font-size: 28px; box-shadow: 0 4px 12px rgba(0,0,0,0.2); display: flex; align-items: center; justify-content: center;"
        >
          {#if navigation.updating}
            <div
              class="mantine-loader"
              style="width: 32px; height: 32px; border-top-color: white;"
            ></div>
          {:else}
            💾
          {/if}
        </button>
      </div>
    {/if}

    <ToastOverlay show={toast.showToast} message={toast.toastMessage} />
  </div>
{/if}

// src/components/MeterReading/MeterReadingApp.jsx
import React, { useState, useCallback } from 'react';
import { formatReading, calculateUsageDisplay } from './utils/formatUtils';
import { calculateWarningFlag } from './utils/warningFlag';
import { useMeterReadings } from './hooks/useMeterReadings';
import { useRoomNavigation } from './hooks/useRoomNavigation';
import { useReadingUpdate } from './hooks/useReadingUpdate';
import { useToast } from './hooks/useToast';
import LoadingOverlay from './components/LoadingOverlay';
import ToastOverlay from './components/ToastOverlay';
import NavigationButtons from './components/NavigationButtons';
import PropertyInfoHeader from './components/PropertyInfoHeader';
import ReadingHistoryTable from './components/ReadingHistoryTable';
import InitialReadingForm from './components/InitialReadingForm';

const MeterReadingApp = () => {
  const {
    loading,
    error,
    propertyId,
    propertyName,
    roomId,
    roomName,
    meterReadings,
    setMeterReadings,
    gasWebAppUrl,
    setError,
    loadMeterReadings,
  } = useMeterReadings();

  const { toastMessage, showToast, displayToast } = useToast();

  const {
    updating,
    isNavigating,
    navigationMessage,
    setUpdating,
    getRoomNavigation,
    handlePreviousRoom,
    handleNextRoom,
    handleBackButton,
    updateSessionStorageCache,
  } = useRoomNavigation({
    propertyId,
    roomId,
    gasWebAppUrl,
    meterReadings,
    setMeterReadings,
    displayToast,
  });

  const { inputErrors, setInputErrors, usageStates, setUsageStates } = useReadingUpdate({
    propertyId,
    roomId,
    gasWebAppUrl,
    meterReadings,
    setMeterReadings,
    displayToast,
    setUpdating,
  });

  // Controlled input values for each reading date
  const [readingValues, setReadingValues] = useState({});

  // Initialize reading values when meterReadings changes
  React.useEffect(() => {
    setReadingValues((prev) => {
      const updated = { ...prev };
      meterReadings.forEach((reading) => {
        if (!(reading.date in updated)) {
          updated[reading.date] = formatReading(reading.currentReading);
        }
      });
      if (!('' in updated)) updated[''] = '';
      return updated;
    });
  }, [meterReadings]);

  const collectReadingsFromState = useCallback(() => {
    const readings = [];

    for (const reading of meterReadings) {
      const date = reading.date;
      const originalValue = formatReading(reading.currentReading);
      const currentValue = readingValues[date] ?? originalValue;

      if (currentValue && currentValue !== originalValue && currentValue.trim() !== '') {
        const numericValue = parseFloat(currentValue);
        if (!isNaN(numericValue) && numericValue >= 0) {
          const inspectionDate = new Intl.DateTimeFormat('ja-CA', {
            timeZone: 'Asia/Tokyo',
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
          }).format(new Date());

          readings.push({
            date: inspectionDate,
            currentReading: currentValue,
            warningFlag: reading.warningFlag || '正常',
          });
        }
      }
    }

    // Also check initial reading form (empty date key)
    const initialValue = readingValues[''] ?? '';
    if (initialValue && initialValue.trim() !== '') {
      const numericValue = parseFloat(initialValue);
      if (!isNaN(numericValue) && numericValue >= 0) {
        const inspectionDate = new Intl.DateTimeFormat('ja-CA', {
          timeZone: 'Asia/Tokyo',
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
        }).format(new Date());

        readings.push({
          date: inspectionDate,
          currentReading: initialValue,
          warningFlag: '正常',
        });
      }
    }

    return readings;
  }, [meterReadings, readingValues]);

  const handleInputChange = useCallback(
    (date, value, reading) => {
      setReadingValues((prev) => ({ ...prev, [date]: value }));
      const previousValue = formatReading(reading.previousReading);
      const numericValue = parseFloat(value);

      if (value === '') {
        setInputErrors((prev) => ({ ...prev, [date]: '' }));
        setUsageStates((prev) => ({
          ...prev,
          [date]: calculateUsageDisplay(value, previousValue),
        }));
      } else if (isNaN(numericValue) || numericValue < 0) {
        setInputErrors((prev) => ({ ...prev, [date]: '0以上の数値を入力' }));
        setUsageStates((prev) => ({ ...prev, [date]: '-' }));
      } else {
        setInputErrors((prev) => ({ ...prev, [date]: '' }));
        const usageDisplay = calculateUsageDisplay(value, previousValue);
        setUsageStates((prev) => ({ ...prev, [date]: usageDisplay }));

        // Real-time warning flag calculation
        const previousReadingValue = parseFloat(reading.previousReading) || 0;
        const previousPreviousReadingValue = parseFloat(reading.previousPreviousReading) || 0;
        const threeTimesPreviousReadingValue = parseFloat(reading.threeTimesPrevious) || 0;

        const warningResult = calculateWarningFlag(
          numericValue,
          previousReadingValue,
          previousPreviousReadingValue,
          threeTimesPreviousReadingValue
        );

        setMeterReadings((prevReadings) =>
          prevReadings.map((r) =>
            r.date === date
              ? {
                  ...r,
                  warningFlag: warningResult.warningFlag,
                  standardDeviation: warningResult.standardDeviation,
                }
              : r
          )
        );
      }
    },
    [setInputErrors, setUsageStates, setMeterReadings]
  );

  const handleInitialInputChange = useCallback(
    (value) => {
      const dateForDataAttribute = '';
      setReadingValues((prev) => ({ ...prev, '': value }));
      const numericValue = parseFloat(value);

      if (value === '') {
        setInputErrors((prev) => ({
          ...prev,
          [dateForDataAttribute]: '初回検針では指示数の入力が必須です。',
        }));
        setUsageStates((prev) => ({ ...prev, [dateForDataAttribute]: '-' }));
      } else if (isNaN(numericValue) || numericValue < 0) {
        setInputErrors((prev) => ({
          ...prev,
          [dateForDataAttribute]: '0以上の数値を入力してください。',
        }));
        setUsageStates((prev) => ({ ...prev, [dateForDataAttribute]: '-' }));
      } else {
        setInputErrors((prev) => ({ ...prev, [dateForDataAttribute]: '' }));
        setUsageStates((prev) => ({
          ...prev,
          [dateForDataAttribute]: calculateUsageDisplay(value, ''),
        }));
      }
    },
    [setInputErrors, setUsageStates]
  );

  const handleUpdateReadings = useCallback(async () => {
    if (!propertyId || !roomId) {
      displayToast('物件IDまたは部屋IDが取得できませんでした。');
      return;
    }

    // Validate: check for empty required fields
    let hasValidationErrors = false;
    for (const reading of meterReadings) {
      const date = reading.date;
      const originalValue = formatReading(reading.currentReading);
      const currentValue = readingValues[date] ?? originalValue;

      if (originalValue === '' && (!currentValue || currentValue.trim() === '')) {
        setInputErrors((prev) => ({ ...prev, [date]: '初回検針では指示数の入力が必須です。' }));
        hasValidationErrors = true;
      }
    }

    if (hasValidationErrors) {
      displayToast('入力値に誤りがあります。各項目のエラーを確認してください。');
      return;
    }

    const updatedReadings = collectReadingsFromState();

    if (updatedReadings.length === 0) {
      displayToast('更新するデータがありません。');
      return;
    }

    setUpdating(true);

    try {
      const currentGasUrl = gasWebAppUrl || sessionStorage.getItem('gasWebAppUrl');
      const params = new URLSearchParams({
        action: 'updateMeterReadings',
        propertyId,
        roomId,
        readings: JSON.stringify(updatedReadings),
      });
      const requestUrl = `${currentGasUrl}?${params}`;

      const [response, cacheUpdateResult] = await Promise.allSettled([
        fetch(requestUrl, { method: 'GET' }),
        updateSessionStorageCache(propertyId, roomId),
      ]);

      if (response.status === 'rejected') {
        throw new Error('ネットワークエラー: ' + response.reason?.message);
      }
      if (!response.value.ok) {
        throw new Error(
          'ネットワークの応答が正しくありませんでした。ステータス: ' + response.value.status
        );
      }

      const result = await response.value.json();

      if (result.success) {
        displayToast('検針データが正常に更新されました');
        setInputErrors({});

        // Reload data
        const [dataReloadResult] = await Promise.allSettled([
          loadMeterReadings(propertyId, roomId),
        ]);
        if (dataReloadResult.status === 'rejected') {
          displayToast(
            'データが更新されました。最新情報を確認するにはページを再読み込みしてください。'
          );
        }
      } else {
        throw new Error(result.error || '指示数の更新に失敗しました。');
      }
    } catch (err) {
      displayToast('更新エラー: ' + err.message);
    } finally {
      setUpdating(false);
    }
  }, [
    propertyId,
    roomId,
    gasWebAppUrl,
    meterReadings,
    readingValues,
    displayToast,
    setUpdating,
    collectReadingsFromState,
  ]);

  const navigation = getRoomNavigation();

  // Loading state
  if (loading) {
    return (
      <>
        <div className="app-header">
          <button
            onClick={() => handleBackButton(propertyId, roomId)}
            className="back-button"
            aria-label="戻る"
          >
            &lt;
          </button>
          <h1 className="header-title">検針情報</h1>
        </div>
        <div className="content-area mantine-container">
          <div className="mantine-stack center">
            <div className="mantine-loader"></div>
            <p className="mantine-text">検針データを読み込んでいます...</p>
          </div>
        </div>
      </>
    );
  }

  // Error state
  if (error) {
    return (
      <>
        <div className="app-header">
          <button
            onClick={() => handleBackButton(propertyId, roomId)}
            className="back-button"
            aria-label="戻る"
          >
            &lt;
          </button>
          <h1 className="header-title">検針情報</h1>
        </div>
        <div className="content-area mantine-container">
          <div className="mantine-stack">
            <div className="mantine-alert">
              <h3 className="mantine-text weight-600">エラー</h3>
              <p className="mantine-text">{String(error || 'エラーが発生しました')}</p>
            </div>
          </div>
        </div>
      </>
    );
  }

  const hasReadingsWithPrevious =
    Array.isArray(meterReadings) &&
    meterReadings.length > 0 &&
    meterReadings.some(
      (reading) =>
        reading.previousReading && reading.previousReading !== '' && reading.previousReading !== 0
    );

  // Main content
  return (
    <>
      {isNavigating && <LoadingOverlay message={navigationMessage} />}
      <div className="app-header">
        <button
          onClick={() => handleBackButton(propertyId, roomId)}
          className="back-button"
          aria-label="戻る"
        >
          &lt;
        </button>
        <h1 className="header-title">検針情報</h1>
      </div>

      <div className="content-area mantine-container">
        <div className="mantine-stack">
          <PropertyInfoHeader propertyName={propertyName} roomName={roomName} />
          <div
            className="mantine-paper reading-history-container"
            style={{ padding: 'var(--mui-spacing-xs)', margin: '0' }}
          >
            <div className="reading-history-header">
              <NavigationButtons
                hasPrevious={navigation.hasPrevious}
                hasNext={navigation.hasNext}
                disabled={updating}
                onPrevious={() => handlePreviousRoom(collectReadingsFromState)}
                onNext={() => handleNextRoom(collectReadingsFromState)}
                variant="header"
              />
            </div>

            {hasReadingsWithPrevious ? (
              <>
                <ReadingHistoryTable
                  meterReadings={meterReadings}
                  readingValues={readingValues}
                  inputErrors={inputErrors}
                  usageStates={usageStates}
                  onInputChange={handleInputChange}
                />

                <NavigationButtons
                  hasPrevious={navigation.hasPrevious}
                  hasNext={navigation.hasNext}
                  disabled={updating}
                  onPrevious={() => handlePreviousRoom(collectReadingsFromState)}
                  onNext={() => handleNextRoom(collectReadingsFromState)}
                  variant="footer"
                />
              </>
            ) : (
              <InitialReadingForm
                readingValue={readingValues['']}
                inputError={inputErrors['']}
                usageState={usageStates['']}
                onInputChange={handleInitialInputChange}
              />
            )}
          </div>
        </div>

        {!loading && !error && (
          <div
            className="fab-container"
            style={{ position: 'fixed', bottom: '20px', right: '20px', zIndex: 1001 }}
          >
            <button
              className="fab-button mantine-button variant-filled"
              onClick={handleUpdateReadings}
              disabled={updating || isNavigating}
              title={hasReadingsWithPrevious ? '指示数を更新' : '初回検針データを保存'}
              style={{
                width: '72px',
                height: '72px',
                borderRadius: '50%',
                fontSize: '28px',
                boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              {updating ? (
                <div
                  className="mantine-loader"
                  style={{ width: '32px', height: '32px', borderTopColor: 'white' }}
                ></div>
              ) : (
                '💾'
              )}
            </button>
          </div>
        )}

        <ToastOverlay show={showToast} message={toastMessage} />
      </div>
    </>
  );
};

export default MeterReadingApp;
