// src/components/RoomSelect/RoomSelectApp.svelte
<script lang="ts">
  import { getGasUrl, gasFetch } from '../../utils/gasClient';
  import NetworkStatusBar from '../NetworkStatusBar.svelte';
  import { validateId } from '../../utils/validateParams';

  import type { Room } from '../../types';

  let rooms: Room[] = $state([]);
  let propertyName: string = $state('物件名読み込み中...');
  let loading: boolean = $state(true);
  let error: string | null = $state(null);
  let propertyId: string = $state('');
  let toastMessage: string = $state('');
  let showToast: boolean = $state(false);
  let toastTimerRef: ReturnType<typeof setTimeout> | null = null;
  let showExitModal: boolean = $state(false);

  function displayToast(message: string): void {
    toastMessage = message;
    showToast = true;
    if (toastTimerRef) clearTimeout(toastTimerRef);
    toastTimerRef = setTimeout(() => {
      showToast = false;
      toastMessage = '';
    }, 3000);
  }

  async function loadRoomData(propId: string): Promise<void> {
    let gasWebAppUrl = sessionStorage.getItem('gasWebAppUrl');
    if (!gasWebAppUrl) {
      gasWebAppUrl = localStorage.getItem('gasWebAppUrl');
      if (gasWebAppUrl) {
        sessionStorage.setItem('gasWebAppUrl', gasWebAppUrl);
      }
    }

    if (!gasWebAppUrl || !gasWebAppUrl.includes('script.google.com')) {
      error = 'GAS Web App URLが設定されていません。';
      loading = false;
      return;
    }

    try {
      // Clean up stale flags from previous navigation
      sessionStorage.removeItem('forceRefreshRooms');

      // Try sessionStorage cache first (always, since handleBackButton updates it optimistically)
      const sessionRooms = sessionStorage.getItem('selectedRooms');
      const sessionPropertyName = sessionStorage.getItem('selectedPropertyName');
      const sessionPropertyId = sessionStorage.getItem('selectedPropertyId');

      if (sessionRooms && sessionPropertyId === propId && sessionPropertyName) {
        try {
          const parsedRooms = JSON.parse(sessionRooms);
          if (Array.isArray(parsedRooms)) {
            rooms = parsedRooms;
            propertyName = sessionPropertyName;
            loading = false;
            setTimeout(() => performBackgroundUpdate(propId, gasWebAppUrl!, parsedRooms), 100);
            return;
          }
        } catch (_) {
          // Continue to API fetch
        }
      }

      try {
        const data: any = await gasFetch('getRoomsLight', {
          propertyId: propId,
          cache: String(Date.now()),
        });
        if (data.success === false) {
          throw new Error(data.error || 'API error');
        }

        const fetchedRooms = data.data?.rooms || data.data || [];
        const fetchedPropertyName =
          data.data?.propertyName || sessionStorage.getItem('selectedPropertyName') || '物件名不明';

        if (!Array.isArray(fetchedRooms)) {
          throw new Error('Invalid data format');
        }

        rooms = fetchedRooms;
        propertyName = fetchedPropertyName;
        sessionStorage.setItem('selectedRooms', JSON.stringify(fetchedRooms));
        sessionStorage.setItem('selectedPropertyName', fetchedPropertyName);
        sessionStorage.setItem('selectedPropertyId', propId);
      } catch (_) {
        const data: any = await gasFetch('getRooms', { propertyId: propId });
        if (!data.success) {
          throw new Error(data.error || 'データの取得に失敗しました');
        }

        let fetchedPropertyName = '物件名不明';
        if (data.data) {
          fetchedPropertyName =
            data.data.propertyName ||
            (data.data.property && data.data.property.name) ||
            data.data.property_name ||
            data.data.name ||
            sessionStorage.getItem('selectedPropertyName') ||
            '物件名不明';
        }

        const fetchedRooms = data.data && Array.isArray(data.data.rooms) ? data.data.rooms : [];
        if (!Array.isArray(fetchedRooms)) {
          throw new Error('部屋データの取得に失敗しました');
        }

        rooms = fetchedRooms;
        propertyName = fetchedPropertyName;
        sessionStorage.setItem('selectedRooms', JSON.stringify(fetchedRooms));
        sessionStorage.setItem('selectedPropertyName', fetchedPropertyName);
        sessionStorage.setItem('selectedPropertyId', propId);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      error = message;
    } finally {
      loading = false;
    }
  }

  async function performBackgroundUpdate(
    propId: string,
    _gasWebAppUrl: string,
    _currentRooms: Room[]
  ): Promise<void> {
    try {
      const data: any = await gasFetch('getRoomsLight', {
        propertyId: propId,
        cache: String(Date.now()),
      });
      if (data.success) {
        const updatedRooms = data.data?.rooms || data.data || [];
        if (Array.isArray(updatedRooms) && updatedRooms.length > 0) {
          // Preserve optimistic update for recently saved room
          const savedRoomId = sessionStorage.getItem('updatedRoomId');
          const savedTime = sessionStorage.getItem('lastUpdateTime');
          if (savedRoomId && savedTime) {
            const elapsed = Date.now() - parseInt(savedTime, 10);
            if (elapsed < 30000) {
              // Within 30s: protect the optimistic update from API cache lag
              const preserved = updatedRooms.map((room: Room) => {
                const rid = String(room.id || room.roomId || '');
                if (rid === savedRoomId) {
                  return {
                    ...room,
                    readingStatus: 'completed',
                    isCompleted: true,
                    readingDateFormatted:
                      room.readingDateFormatted ||
                      new Intl.DateTimeFormat('ja-JP', {
                        timeZone: 'Asia/Tokyo',
                        month: 'long',
                        day: 'numeric',
                      }).format(new Date()),
                  };
                }
                return room;
              });
              rooms = preserved;
              sessionStorage.setItem('selectedRooms', JSON.stringify(preserved));
              return;
            }
          }
          rooms = updatedRooms;
          sessionStorage.setItem('selectedRooms', JSON.stringify(updatedRooms));
        }
      }
    } catch (_) {
      // Background update failure is non-critical
    }
  }

  function handleRoomClick(room: Room): void {
    if (room.isNotNeeded === true) {
      displayToast('この部屋は検針不要に設定されています。');
      return;
    }

    const roomId = String(room.id || room.roomId || '');
    const gasUrl = getGasUrl();
    if (gasUrl) {
      sessionStorage.setItem('gasWebAppUrl', gasUrl);
    }
    window.location.href = `/reading/?propertyId=${encodeURIComponent(propertyId)}&roomId=${encodeURIComponent(roomId)}`;
  }

  function handleBackButton(): void {
    window.location.href = '/property/';
  }

  function handleExitYes(): void {
    window.close();
    document.body.innerHTML =
      '<div style="display:flex;align-items:center;justify-content:center;height:100vh;font-family:sans-serif;color:#333;font-size:1.125rem;">検針が完了しました。このタブを閉じてください。</div>';
  }

  function handleExitNo(): void {
    showExitModal = false;
    window.location.href = '/property/';
  }

  async function handleCompleteInspection(): Promise<void> {
    if (!propertyId) {
      displayToast('物件IDが取得できませんでした');
      return;
    }

    const gasUrl = sessionStorage.getItem('gasWebAppUrl');
    if (!gasUrl) {
      displayToast('Web App URLが設定されていません');
      return;
    }

    try {
      const today = new Date();
      const completionDate =
        today.getFullYear() +
        '-' +
        String(today.getMonth() + 1).padStart(2, '0') +
        '-' +
        String(today.getDate()).padStart(2, '0');

      const result: any = await gasFetch('completeInspection', { propertyId, completionDate });

      if (result.success) {
        displayToast(`検針完了日を ${completionDate} で保存しました！`);
        showExitModal = true;
      } else {
        throw new Error(result.error || '検針完了処理に失敗しました');
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      displayToast(`検針完了処理でエラーが発生しました: ${message}`);
    }
  }

  $effect(() => {
    window.scrollTo(0, 0);

    const urlParams = new URLSearchParams(window.location.search);
    const propId = urlParams.get('propertyId');

    if (!propId) {
      error = '物件IDが指定されていません。';
      loading = false;
      return;
    }

    const validation = validateId(propId, '物件ID');
    if (!validation.valid) {
      error = validation.error ?? '物件IDが無効です';
      loading = false;
      return;
    }

    propertyId = propId;
    loadRoomData(propId);
  });

  $effect(() => {
    return () => {
      if (toastTimerRef) clearTimeout(toastTimerRef);
    };
  });
</script>

{#if loading}
  <div>
    <NetworkStatusBar />
    <header class="MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic mui-elevation-4">
      <nav class="MuiToolbar-root MuiToolbar-regular" aria-label="部屋選択ナビゲーション">
        <button
          class="MuiIconButton-root MuiIconButton-colorInherit"
          onclick={handleBackButton}
          aria-label="戻る"
        >
          <span class="material-icons MuiSvgIcon-root">arrow_back</span>
        </button>
        <span class="MuiTypography-root MuiTypography-h6 app-title">部屋選択</span>
      </nav>
    </header>
    <main class="MuiContainer-root MuiContainer-maxWidthLg" style="padding-top: 32px;">
      <div class="loading-container">
        <span class="MuiCircularProgress-root" aria-label="読み込み中"></span>
        <span class="MuiTypography-root MuiTypography-body1"> 部屋データを読み込み中... </span>
      </div>
    </main>
  </div>
{:else if error}
  <div>
    <NetworkStatusBar />
    <header class="MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic mui-elevation-4">
      <nav class="MuiToolbar-root MuiToolbar-regular" aria-label="部屋選択ナビゲーション">
        <button
          class="MuiIconButton-root MuiIconButton-colorInherit"
          onclick={handleBackButton}
          aria-label="戻る"
        >
          <span class="material-icons MuiSvgIcon-root">arrow_back</span>
        </button>
        <span class="MuiTypography-root MuiTypography-h6 app-title">部屋選択</span>
      </nav>
    </header>
    <main class="MuiContainer-root MuiContainer-maxWidthLg" style="padding-top: 32px;">
      <div class="MuiAlert-root MuiAlert-standardError" role="alert">
        <span class="MuiAlert-message">{String(error)}</span>
      </div>
    </main>
  </div>
{:else}
  <div>
    <header class="MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic mui-elevation-4">
      <nav class="MuiToolbar-root MuiToolbar-regular" aria-label="部屋選択ナビゲーション">
        <button
          class="MuiIconButton-root MuiIconButton-colorInherit"
          onclick={handleBackButton}
          aria-label="戻る"
        >
          <span class="material-icons MuiSvgIcon-root">arrow_back</span>
        </button>
        <span class="MuiTypography-root MuiTypography-h6 app-title">部屋選択</span>
      </nav>
    </header>

    <main class="MuiContainer-root MuiContainer-maxWidthLg" style="padding-top: 32px;">
      <section
        class="MuiCard-root MuiPaper-root MuiPaper-elevation1 property-card"
        aria-label="物件情報"
      >
        <div class="MuiCardHeader-root property-header">
          <span class="material-icons MuiSvgIcon-root property-icon" aria-hidden="true">
            home
          </span>
          <span class="MuiTypography-root MuiTypography-h5">{propertyName}</span>
        </div>
      </section>

      <section class="room-grid" aria-label="部屋一覧" role="list">
        {#if rooms.length === 0}
          <div class="no-rooms-message">部屋データがありません</div>
        {:else}
          {#each rooms as room, index (room.id || index)}
            {@const isSkipInspection = room.isNotNeeded === true}
            {@const isCompleted = room.readingStatus === 'completed' || room.isCompleted}
            {@const statusIcon = isSkipInspection
              ? 'block'
              : isCompleted
                ? 'check_circle'
                : 'warning'}
            {@const statusColor = isSkipInspection
              ? '#9e9e9e'
              : isCompleted
                ? '#2e7d32'
                : '#ed6c02'}
            {@const statusText = isSkipInspection
              ? '検針不要'
              : isCompleted
                ? room.readingDateFormatted
                  ? `検針済み：${String(room.readingDateFormatted)}`
                  : '検針済み'
                : '未検針'}
            {@const cardClasses = isSkipInspection
              ? 'MuiCard-root MuiPaper-root MuiPaper-elevation1 MuiCardActionArea-root room-card status-skip'
              : isCompleted
                ? 'MuiCard-root MuiPaper-root MuiPaper-elevation1 MuiCardActionArea-root room-card status-completed'
                : 'MuiCard-root MuiPaper-root MuiPaper-elevation1 MuiCardActionArea-root room-card status-pending'}
            <button
              type="button"
              class={cardClasses}
              disabled={isSkipInspection}
              aria-label={String(room.name || room['部屋名'] || room.id || '不明') +
                (isSkipInspection ? ' 検針不要' : isCompleted ? ' 検針済み' : ' 未検針')}
              onclick={() => handleRoomClick(room)}
            >
              <div class="MuiCardContent-root room-info-row">
                <span
                  class="material-icons MuiSvgIcon-root status-icon"
                  aria-hidden="true"
                  style="color: {statusColor};"
                >
                  {statusIcon}
                </span>
                <span class="MuiTypography-root MuiTypography-h6 room-name">
                  {String(room.name || room['部屋名'] || room.id || '不明')}
                </span>
                <span class="MuiTypography-root MuiTypography-body2 room-status">
                  {statusText}
                </span>
              </div>
            </button>
          {/each}
        {/if}
      </section>

      {#if rooms.length > 0}
        <div class="complete-button-container">
          <button
            class="MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge complete-button"
            onclick={handleCompleteInspection}
            aria-label="この物件の検針を完了する"
          >
            <span class="material-icons MuiSvgIcon-root" aria-hidden="true"> check_circle </span>
            <span class="MuiButton-label">この物件の検針を完了する</span>
          </button>
        </div>
      {/if}
    </main>

    {#if showToast}
      <div role="status" aria-live="polite" class="toast-inline">
        {toastMessage}
      </div>
    {/if}

    {#if showExitModal}
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="exit-modal-title"
        style="position: fixed; top: 0; left: 0; width: 100vw; height: 100vh; background-color: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; z-index: 2147483647;"
      >
        <div
          style="background-color: #fff; border-radius: 16px; padding: 32px; max-width: 360px; width: 90%; box-shadow: 0 8px 32px rgba(0,0,0,0.2);"
        >
          <h3
            id="exit-modal-title"
            style="margin: 0 0 16px 0; font-size: 1.125rem; font-weight: 600;"
          >
            アプリを終了しますか？
          </h3>
          <div style="display: flex; gap: 12px; justify-content: center;">
            <button
              onclick={handleExitYes}
              style="flex: 1; padding: 10px 16px; border-radius: 8px; border: none; background-color: var(--mui-palette-primary-main, #1976d2); color: #fff; cursor: pointer; font-weight: 600; font-size: 1rem;"
            >
              はい
            </button>
            <button
              onclick={handleExitNo}
              style="flex: 1; padding: 10px 16px; border-radius: 8px; border: 1px solid #ccc; background-color: #fff; cursor: pointer; font-size: 1rem;"
            >
              いいえ
            </button>
          </div>
        </div>
      </div>
    {/if}
  </div>
{/if}

// src/components/RoomSelect/RoomSelectApp.jsx
import React, { useState, useEffect, useCallback } from 'react';
import { getGasUrl } from '../../utils/gasClient';
import { validateId } from '../../utils/validateParams';

const RoomSelectApp = () => {
  const [rooms, setRooms] = useState([]);
  const [propertyName, setPropertyName] = useState('物件名読み込み中...');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [propertyId, setPropertyId] = useState('');
  const [toastMessage, setToastMessage] = useState('');
  const [showToast, setShowToast] = useState(false);
  const toastTimerRef = React.useRef(null);

  const displayToast = useCallback((message) => {
    setToastMessage(message);
    setShowToast(true);
    if (toastTimerRef.current) clearTimeout(toastTimerRef.current);
    toastTimerRef.current = setTimeout(() => {
      setShowToast(false);
      setToastMessage('');
    }, 3000);
  }, []);

  useEffect(() => {
    window.scrollTo(0, 0);

    const urlParams = new URLSearchParams(window.location.search);
    const propId = urlParams.get('propertyId');

    if (!propId) {
      setError('物件IDが指定されていません。');
      setLoading(false);
      return;
    }

    const validation = validateId(propId, '物件ID');
    if (!validation.valid) {
      setError(validation.error);
      setLoading(false);
      return;
    }

    setPropertyId(propId);
    loadRoomData(propId);
  }, []);

  const loadRoomData = async (propId) => {
    let gasWebAppUrl = sessionStorage.getItem('gasWebAppUrl');
    if (!gasWebAppUrl) {
      gasWebAppUrl = localStorage.getItem('gasWebAppUrl');
      if (gasWebAppUrl) {
        sessionStorage.setItem('gasWebAppUrl', gasWebAppUrl);
      }
    }

    if (!gasWebAppUrl || !gasWebAppUrl.includes('script.google.com')) {
      setError('GAS Web App URLが設定されていません。');
      setLoading(false);
      return;
    }

    try {
      // Check session storage for fast display (from property select navigation)
      const forceRefresh = sessionStorage.getItem('forceRefreshRooms') === 'true';
      if (forceRefresh) {
        sessionStorage.removeItem('forceRefreshRooms');
        sessionStorage.removeItem('updatedRoomId');
        sessionStorage.removeItem('lastUpdateTime');
      }

      if (!forceRefresh) {
        const sessionRooms = sessionStorage.getItem('selectedRooms');
        const sessionPropertyName = sessionStorage.getItem('selectedPropertyName');
        const sessionPropertyId = sessionStorage.getItem('selectedPropertyId');

        if (sessionRooms && sessionPropertyId === propId && sessionPropertyName) {
          try {
            const parsedRooms = JSON.parse(sessionRooms);
            if (Array.isArray(parsedRooms)) {
              setRooms(parsedRooms);
              setPropertyName(sessionPropertyName);
              setLoading(false);
              // Background delta update
              setTimeout(() => performBackgroundUpdate(propId, gasWebAppUrl, parsedRooms), 100);
              return;
            }
          } catch (parseError) {
            // Continue to API fetch
          }
        }
      }

      // Try light API first, fallback to legacy
      try {
        const fetchUrl = `${gasWebAppUrl}?action=getRoomsLight&propertyId=${encodeURIComponent(propId)}&cache=${Date.now()}`;
        const response = await fetch(fetchUrl);

        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`);
        }

        const data = await response.json();
        if (data.success === false) {
          throw new Error(data.error || 'API error');
        }

        const fetchedRooms = data.data?.rooms || data.data || [];
        const fetchedPropertyName =
          data.data?.propertyName || sessionStorage.getItem('selectedPropertyName') || '物件名不明';

        if (!Array.isArray(fetchedRooms)) {
          throw new Error('Invalid data format');
        }

        setRooms(fetchedRooms);
        setPropertyName(fetchedPropertyName);
        sessionStorage.setItem('selectedRooms', JSON.stringify(fetchedRooms));
        sessionStorage.setItem('selectedPropertyName', fetchedPropertyName);
        sessionStorage.setItem('selectedPropertyId', propId);
      } catch (lightError) {
        // Fallback to legacy API
        const fetchUrl = `${gasWebAppUrl}?action=getRooms&propertyId=${encodeURIComponent(propId)}`;
        const response = await fetch(fetchUrl);

        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`);
        }

        const data = await response.json();
        if (!data.success) {
          throw new Error(data.error || 'データの取得に失敗しました');
        }

        let fetchedPropertyName = '物件名不明';
        if (data.data) {
          fetchedPropertyName =
            data.data.propertyName ||
            (data.data.property && data.data.property.name) ||
            data.data.property_name ||
            data.data.name ||
            sessionStorage.getItem('selectedPropertyName') ||
            '物件名不明';
        }

        const fetchedRooms = data.data && Array.isArray(data.data.rooms) ? data.data.rooms : [];
        if (!Array.isArray(fetchedRooms)) {
          throw new Error('部屋データの取得に失敗しました');
        }

        setRooms(fetchedRooms);
        setPropertyName(fetchedPropertyName);
        sessionStorage.setItem('selectedRooms', JSON.stringify(fetchedRooms));
        sessionStorage.setItem('selectedPropertyName', fetchedPropertyName);
        sessionStorage.setItem('selectedPropertyId', propId);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const performBackgroundUpdate = async (propId, gasWebAppUrl, currentRooms) => {
    try {
      const fetchUrl = `${gasWebAppUrl}?action=getRoomsLight&propertyId=${encodeURIComponent(propId)}&cache=${Date.now()}`;
      const response = await fetch(fetchUrl);
      if (!response.ok) return;

      const data = await response.json();
      if (data.success) {
        const updatedRooms = data.data?.rooms || data.data || [];
        if (Array.isArray(updatedRooms) && updatedRooms.length > 0) {
          setRooms(updatedRooms);
          sessionStorage.setItem('selectedRooms', JSON.stringify(updatedRooms));
        }
      }
    } catch (err) {
      // Background update failure is non-critical
    }
  };

  const handleRoomClick = useCallback(
    (room) => {
      if (room.isNotNeeded === true) {
        displayToast('この部屋は検針不要に設定されています。');
        return;
      }

      const roomId = String(room.id || room.roomId || '');
      const gasUrl = getGasUrl();
      if (gasUrl) {
        sessionStorage.setItem('gasWebAppUrl', gasUrl);
      }
      window.location.href = `/reading/?propertyId=${encodeURIComponent(propertyId)}&roomId=${encodeURIComponent(roomId)}`;
    },
    [propertyId]
  );

  const handleBackButton = useCallback(() => {
    window.location.href = '/property/';
  }, []);

  const handleCompleteInspection = useCallback(async () => {
    if (!propertyId) {
      displayToast('物件IDが取得できませんでした');
      return;
    }

    const gasUrl = sessionStorage.getItem('gasWebAppUrl');
    if (!gasUrl) {
      displayToast('Web App URLが設定されていません');
      return;
    }

    try {
      const today = new Date();
      const completionDate =
        today.getFullYear() +
        '-' +
        String(today.getMonth() + 1).padStart(2, '0') +
        '-' +
        String(today.getDate()).padStart(2, '0');

      const response = await fetch(
        `${gasUrl}?action=completeInspection&propertyId=${propertyId}&completionDate=${completionDate}`,
        {
          method: 'GET',
          headers: { Accept: 'application/json' },
        }
      );

      if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);

      const result = await response.json();

      if (result.success) {
        displayToast(`検針完了日を ${completionDate} で保存しました！`);
        setTimeout(() => window.location.reload(), 1500);
      } else {
        throw new Error(result.error || '検針完了処理に失敗しました');
      }
    } catch (err) {
      displayToast(`検針完了処理でエラーが発生しました: ${err.message}`);
    }
  }, [propertyId]);

  // Cleanup timers on unmount
  useEffect(() => {
    return () => {
      if (toastTimerRef.current) clearTimeout(toastTimerRef.current);
    };
  }, []);

  // Loading state
  if (loading) {
    return (
      <div>
        <header
          className="MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic mui-elevation-4"
          role="banner"
        >
          <nav className="MuiToolbar-root MuiToolbar-regular" aria-label="部屋選択ナビゲーション">
            <button
              className="MuiIconButton-root MuiIconButton-colorInherit"
              onClick={handleBackButton}
              aria-label="戻る"
            >
              <span className="material-icons MuiSvgIcon-root">arrow_back</span>
            </button>
            <span className="MuiTypography-root MuiTypography-h6 app-title">部屋選択</span>
          </nav>
        </header>
        <main className="MuiContainer-root MuiContainer-maxWidthLg" style={{ paddingTop: '32px' }}>
          <div className="loading-container">
            <span className="MuiCircularProgress-root" aria-label="読み込み中"></span>
            <span className="MuiTypography-root MuiTypography-body1">
              部屋データを読み込み中...
            </span>
          </div>
        </main>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div>
        <header
          className="MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic mui-elevation-4"
          role="banner"
        >
          <nav className="MuiToolbar-root MuiToolbar-regular" aria-label="部屋選択ナビゲーション">
            <button
              className="MuiIconButton-root MuiIconButton-colorInherit"
              onClick={handleBackButton}
              aria-label="戻る"
            >
              <span className="material-icons MuiSvgIcon-root">arrow_back</span>
            </button>
            <span className="MuiTypography-root MuiTypography-h6 app-title">部屋選択</span>
          </nav>
        </header>
        <main className="MuiContainer-root MuiContainer-maxWidthLg" style={{ paddingTop: '32px' }}>
          <div className="MuiAlert-root MuiAlert-standardError" role="alert">
            <span className="MuiAlert-message">{String(error)}</span>
          </div>
        </main>
      </div>
    );
  }

  // Main content
  return (
    <div>
      <header
        className="MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic mui-elevation-4"
        role="banner"
      >
        <nav className="MuiToolbar-root MuiToolbar-regular" aria-label="部屋選択ナビゲーション">
          <button
            className="MuiIconButton-root MuiIconButton-colorInherit"
            onClick={handleBackButton}
            aria-label="戻る"
          >
            <span className="material-icons MuiSvgIcon-root">arrow_back</span>
          </button>
          <span className="MuiTypography-root MuiTypography-h6 app-title">部屋選択</span>
        </nav>
      </header>

      <main className="MuiContainer-root MuiContainer-maxWidthLg" style={{ paddingTop: '32px' }}>
        {/* Property name card */}
        <section
          className="MuiCard-root MuiPaper-root MuiPaper-elevation1 property-card"
          aria-label="物件情報"
        >
          <div className="MuiCardHeader-root property-header">
            <span className="material-icons MuiSvgIcon-root property-icon" aria-hidden="true">
              home
            </span>
            <span className="MuiTypography-root MuiTypography-h5">{propertyName}</span>
          </div>
        </section>

        {/* Room grid */}
        <section className="room-grid" aria-label="部屋一覧" role="list">
          {rooms.length === 0 ? (
            <div className="no-rooms-message">部屋データがありません</div>
          ) : (
            rooms.map((room, index) => {
              const isSkipInspection = room.isNotNeeded === true;
              const isCompleted = room.readingStatus === 'completed' || room.isCompleted;

              let statusIcon, statusColor, statusText;
              if (isSkipInspection) {
                statusIcon = 'block';
                statusColor = '#9e9e9e';
                statusText = '検針不要';
              } else if (isCompleted) {
                statusIcon = 'check_circle';
                statusColor = '#2e7d32';
                statusText = room.readingDateFormatted
                  ? `検針済み：${String(room.readingDateFormatted)}`
                  : '検針済み';
              } else {
                statusIcon = 'warning';
                statusColor = '#ed6c02';
                statusText = '未検針';
              }

              let cardClasses =
                'MuiCard-root MuiPaper-root MuiPaper-elevation1 MuiCardActionArea-root room-card';
              if (isSkipInspection) {
                cardClasses += ' status-skip';
              } else if (isCompleted) {
                cardClasses += ' status-completed';
              } else {
                cardClasses += ' status-pending';
              }

              return (
                <div
                  key={room.id || index}
                  className={cardClasses}
                  tabIndex={isSkipInspection ? -1 : 0}
                  role={isSkipInspection ? 'presentation' : 'button'}
                  aria-label={
                    String(room.name || room['部屋名'] || room.id || '不明') +
                    (isSkipInspection ? ' 検針不要' : isCompleted ? ' 検針済み' : ' 未検針')
                  }
                  onClick={() => handleRoomClick(room)}
                >
                  <div className="MuiCardContent-root room-info-row">
                    <span
                      className="material-icons MuiSvgIcon-root status-icon"
                      aria-hidden="true"
                      style={{ color: statusColor }}
                    >
                      {statusIcon}
                    </span>
                    <span className="MuiTypography-root MuiTypography-h6 room-name">
                      {String(room.name || room['部屋名'] || room.id || '不明')}
                    </span>
                    <span className="MuiTypography-root MuiTypography-body2 room-status">
                      {statusText}
                    </span>
                  </div>
                </div>
              );
            })
          )}
        </section>

        {/* Complete inspection button */}
        {rooms.length > 0 && (
          <div className="complete-button-container">
            <button
              className="MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge complete-button"
              onClick={handleCompleteInspection}
              aria-label="この物件の検針を完了する"
            >
              <span className="material-icons MuiSvgIcon-root" aria-hidden="true">
                check_circle
              </span>
              <span className="MuiButton-label">この物件の検針を完了する</span>
            </button>
          </div>
        )}
      </main>

      {showToast && (
        <div
          style={{
            position: 'fixed',
            bottom: '20px',
            left: '50%',
            transform: 'translateX(-50%)',
            backgroundColor: 'var(--mui-palette-primary-main, #1976d2)',
            color: 'white',
            padding: '12px 24px',
            borderRadius: '8px',
            fontSize: '0.95rem',
            fontWeight: 500,
            boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
            zIndex: 10000,
            textAlign: 'center',
            maxWidth: '90vw',
            animation: 'fadeIn 0.3s ease',
          }}
        >
          {toastMessage}
        </div>
      )}
    </div>
  );
};

export default RoomSelectApp;
